sudo: required
language: node_js
node_js:
  - 'iojs'
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - npm install -g gulp
  - npm install -g http-server
install:
  - bower install
  - npm install
script:
  - http-server
  - gulp
